version: '3'
services:

  # Build project dependencies
  build:
    command: >-
      sh -c "
        mkdir -p build dist &&
        pip install fest==5.0.0 -t build &&
        cp lambda.py build
      "
    image: lambci/lambda:build-python3.7
    volumes:
    - ./:/var/task

  # Deploy to AWS
  terraform:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      TF_VAR_release:
      TF_VAR_repo:
    image: hashicorp/terraform
    volumes:
      - ~/.aws:/root/.aws
      - ./:/terraform
    working_dir: /terraform
